### ISSUE TITLE
File corruption 

### ISSUE THREAD

**Issue by AlhassaneDiawara** [docker/getting-started-todo-app#26]
Hello, 

I tried to make a docker compose, and I received the following message: 

![image](https://github.com/user-attachments/assets/487a1a94-b6d7-4785-b073-3201d6a1630d)

Can you help me to solve the issue please ? 

Thank you 

Alhassane

**Comment by ajeetraina** [comment]
@AlhassaneDiawara Can you run these below commands manually for backend/ and client/ directory once?

```
cd client
npm install
```

```
cd ../backend
npm install
```

and then try to run `docker compose up -d --build` to see if that works.

**Comment by AlhassaneDiawara** [comment]
Hi @ajeetraina , 

I followed your instructions.

First, I did an npm install on each folders (Backend & Client). it seems that no vulnerabilities was found...see the printscreen below.

![image](https://github.com/user-attachments/assets/96ce965b-34e3-48d5-8369-7663a10fac8c)

Then, I tried to compose again...but the issue is still the same...I do think I have issues with Yarn.

![image](https://github.com/user-attachments/assets/bcc37393-2b1c-4235-8c7a-058379cdef06)

I tried first to work on the getting-started-todo-app from my professional laptop, and I had issues with TLS and Yarn (due to strong network security policy in my company), so I tried on my laptop 2 outside of the company's network....

**Comment by ajeetraina** [comment]
@AlhassaneDiawara Yes, it seems there's something to do with a corporate proxy preventing you from downloading external packages. Someone in the past reported the same issue.

**Comment by AlhassaneDiawara** [comment]
@ajeetraina I tried in emergency with a "home" network (from my phone...thank you 5G !), and it works ! 

![image](https://github.com/user-attachments/assets/ba8edaaf-150a-4e1b-888d-929320e3a63c)


I do think that the requests for updating the dependencies are impossible due to security policies in several companies. I will ask some informations to my IT team for a potential workaround.

Thank you for your help ! 

Alhassane

**Comment by AlhassaneDiawara** [comment]
@ajeetraina I tried in emergency with a "home" network (from my phone...thank you 5G !), and it works ! 

![image](https://github.com/user-attachments/assets/ba8edaaf-150a-4e1b-888d-929320e3a63c)


I do think that the requests for updating the dependencies are impossible due to security policies in several companies. I will ask some informations to my IT team for a potential workaround.

Thank you for your help ! 

Alhassane
