### ISSUE TITLE
MySql port error on macOS

### ISSUE THREAD

**Issue by Eason-Ruan** [docker/getting-started-todo-app#28]
It seems that the mysql container is listening on port: 80 on default, but backend container request at port: 3306, leading to the request 502. Modifying Mysql setup in compose.yml can fix the problem. (Changing the port to 3306)

**Comment by mikesir87** [comment]
The MySQL container is not configured to expose any ports. However, there is another service using port 80 (the Traefik proxy). The database is accessible from the backend using the standard MySQL port of 3306 through the container networking (doesn't need to be exposed).

If you're still having troubles, feel free to comment back and we can continue troubleshooting.
